#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-calculator
Version  : 42.0
Release  : 41
URL      : https://download.gnome.org/sources/gnome-calculator/42/gnome-calculator-42.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-calculator/42/gnome-calculator-42.0.tar.xz
Summary  : GNOME Calculator Libray GTK Interface
Group    : Development/Tools
License  : GPL-3.0
Requires: gnome-calculator-bin = %{version}-%{release}
Requires: gnome-calculator-data = %{version}-%{release}
Requires: gnome-calculator-lib = %{version}-%{release}
Requires: gnome-calculator-libexec = %{version}-%{release}
Requires: gnome-calculator-license = %{version}-%{release}
Requires: gnome-calculator-locales = %{version}-%{release}
Requires: gnome-calculator-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gmp-dev
BuildRequires : gtksourceview
BuildRequires : itstool
BuildRequires : libgee-dev
BuildRequires : mpc-dev
BuildRequires : mpfr-dev
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : pkgconfig(gtksourceview-4)
BuildRequires : pkgconfig(gtksourceview-5)
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : vala-dev

%description
# GNOME Calculator [![Build Status](https://gitlab.gnome.org/GNOME/gnome-calculator/badges/master/build.svg)](https://gitlab.gnome.org/GNOME/gnome-calculator/pipelines)

%package bin
Summary: bin components for the gnome-calculator package.
Group: Binaries
Requires: gnome-calculator-data = %{version}-%{release}
Requires: gnome-calculator-libexec = %{version}-%{release}
Requires: gnome-calculator-license = %{version}-%{release}

%description bin
bin components for the gnome-calculator package.


%package data
Summary: data components for the gnome-calculator package.
Group: Data

%description data
data components for the gnome-calculator package.


%package dev
Summary: dev components for the gnome-calculator package.
Group: Development
Requires: gnome-calculator-lib = %{version}-%{release}
Requires: gnome-calculator-bin = %{version}-%{release}
Requires: gnome-calculator-data = %{version}-%{release}
Provides: gnome-calculator-devel = %{version}-%{release}
Requires: gnome-calculator = %{version}-%{release}

%description dev
dev components for the gnome-calculator package.


%package doc
Summary: doc components for the gnome-calculator package.
Group: Documentation
Requires: gnome-calculator-man = %{version}-%{release}

%description doc
doc components for the gnome-calculator package.


%package lib
Summary: lib components for the gnome-calculator package.
Group: Libraries
Requires: gnome-calculator-data = %{version}-%{release}
Requires: gnome-calculator-libexec = %{version}-%{release}
Requires: gnome-calculator-license = %{version}-%{release}

%description lib
lib components for the gnome-calculator package.


%package libexec
Summary: libexec components for the gnome-calculator package.
Group: Default
Requires: gnome-calculator-license = %{version}-%{release}

%description libexec
libexec components for the gnome-calculator package.


%package license
Summary: license components for the gnome-calculator package.
Group: Default

%description license
license components for the gnome-calculator package.


%package locales
Summary: locales components for the gnome-calculator package.
Group: Default

%description locales
locales components for the gnome-calculator package.


%package man
Summary: man components for the gnome-calculator package.
Group: Default

%description man
man components for the gnome-calculator package.


%prep
%setup -q -n gnome-calculator-42.0
cd %{_builddir}/gnome-calculator-42.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648358203
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-calculator
cp %{_builddir}/gnome-calculator-42.0/COPYING %{buildroot}/usr/share/package-licenses/gnome-calculator/8624bcdae55baeef00cd11d5dfcfa60f68710a02
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-calculator

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gcalccmd
/usr/bin/gnome-calculator

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GCalc-2.typelib
/usr/lib64/girepository-1.0/GCi-1.typelib
/usr/share/applications/org.gnome.Calculator.desktop
/usr/share/dbus-1/services/org.gnome.Calculator.SearchProvider.service
/usr/share/devhelp/books/GCalc-2/GCalc-2.devhelp2
/usr/share/devhelp/books/GCalc-2/GCalc.AssigError.INVALID_STRUCTURE_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.AssigError.html
/usr/share/devhelp/books/GCalc-2/GCalc.Assign.Assign.html
/usr/share/devhelp/books/GCalc-2/GCalc.Assign.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.Constant.complex.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.Constant.double.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.Constant.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.Constant.integer.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.Constant.unsigned_integer.html
/usr/share/devhelp/books/GCalc-2/GCalc.Constant.html
/usr/share/devhelp/books/GCalc-2/GCalc.Division.Division.html
/usr/share/devhelp/books/GCalc-2/GCalc.Division.html
/usr/share/devhelp/books/GCalc-2/GCalc.Equation.Equation.html
/usr/share/devhelp/books/GCalc-2/GCalc.Equation.html
/usr/share/devhelp/books/GCalc-2/GCalc.EquationManager.EquationManager.html
/usr/share/devhelp/books/GCalc-2/GCalc.EquationManager.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorExpression.ErrorExpression.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorExpression.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorResult.ErrorResult.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorResult.expression.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorResult.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorResult.message.html
/usr/share/devhelp/books/GCalc-2/GCalc.ErrorResult.to_string.html
/usr/share/devhelp/books/GCalc-2/GCalc.Expression.Expression.html
/usr/share/devhelp/books/GCalc-2/GCalc.Expression.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.ExpressionContainer.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.add.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.find.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.find_named.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.get_item.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.get_item_type.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.get_n_items.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.get_object.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.parent.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.remove.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionContainer.remove_at.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.ExpressionHashMap.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.add.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.find_named.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.parent.html
/usr/share/devhelp/books/GCalc-2/GCalc.ExpressionHashMap.remove.html
/usr/share/devhelp/books/GCalc-2/GCalc.Function.Function.html
/usr/share/devhelp/books/GCalc-2/GCalc.Function.Function.with_name.html
/usr/share/devhelp/books/GCalc-2/GCalc.Function.html
/usr/share/devhelp/books/GCalc-2/GCalc.Function.n_params.html
/usr/share/devhelp/books/GCalc-2/GCalc.Function.name.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAcos.FunctionAcos.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAcos.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAcosh.FunctionAcosh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAcosh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAsin.FunctionAsin.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAsin.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAsinh.FunctionAsinh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAsinh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAtan.FunctionAtan.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAtan.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAtanh.FunctionAtanh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionAtanh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionCos.FunctionCos.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionCos.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionCosh.FunctionCosh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionCosh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionError.INVALID_PARAMETERS_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionError.INVOCATION_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionError.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionExp.FunctionExp.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionExp.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionLog.FunctionLog.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionLog.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSin.FunctionSin.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSin.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSinh.FunctionSinh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSinh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSqrt.FunctionSqrt.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionSqrt.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionTan.FunctionTan.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionTan.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionTanh.FunctionTanh.html
/usr/share/devhelp/books/GCalc-2/GCalc.FunctionTanh.html
/usr/share/devhelp/books/GCalc-2/GCalc.Group.Group.html
/usr/share/devhelp/books/GCalc-2/GCalc.Group.html
/usr/share/devhelp/books/GCalc-2/GCalc.GroupError.INVALID_INTERNAL_TERM.html
/usr/share/devhelp/books/GCalc-2/GCalc.GroupError.INVALID_POLYNOMIAL.html
/usr/share/devhelp/books/GCalc-2/GCalc.GroupError.html
/usr/share/devhelp/books/GCalc-2/GCalc.Hashable.hash.html
/usr/share/devhelp/books/GCalc-2/GCalc.Hashable.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathAssign.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathAssign.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathBinaryOperator.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.add.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.divide.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.multiply.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.neg.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.pow.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstant.subtract.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantComplex.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantComplex.imag.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantComplex.real.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantComplex.zero.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantNumber.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathConstantNumber.value.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathDivision.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquation.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquation.variables.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquationManager.equations.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquationManager.find_variable.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquationManager.functions.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathEquationManager.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathErrorResult.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathErrorResult.message.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathExpression.expressions.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathExpression.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathExpression.parent.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathExpression.solve.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathExpression.to_string.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.closed.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.n_params.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.name.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.param_types.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathFunction.verify_params.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.Level.ONE.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.Level.THREE.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.Level.TWO.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.Level.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.closed.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathGroup.level.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathMinus.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathMultiply.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathOperator.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathParameter.get_value.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathParameter.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathParameter.set_value.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathPlus.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathPolynomial.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathPolynomial.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathPow.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathResult.expression.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathResult.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathResult.to_string.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathTerm.add.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathTerm.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathTerm.evaluate_constants.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathTerm.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.bind.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.binded.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.evaluate.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.name.html
/usr/share/devhelp/books/GCalc-2/GCalc.MathVariable.value.html
/usr/share/devhelp/books/GCalc-2/GCalc.Minus.Minus.html
/usr/share/devhelp/books/GCalc-2/GCalc.Minus.html
/usr/share/devhelp/books/GCalc-2/GCalc.Multiply.Multiply.html
/usr/share/devhelp/books/GCalc-2/GCalc.Multiply.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parameter.Parameter.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parameter.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.Parser.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.ASSIGN.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.CARRET.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.CLOSE_BRACE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.CLOSE_BRACKET.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.CLOSE_PARENS.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.COLON.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.COMMA.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.CURRENCY_SYMBOL.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.DIV.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.DOT.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.DOUBLE_COLON.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.ELLIPSIS.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.EOF.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.HASH.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.IDENTIFIER.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.INTEGER_LITERAL.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.INTERR.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.MINUS.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.NONE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OPEN_BRACE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OPEN_BRACKET.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OPEN_PARENS.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_AND.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_COALESCING.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_DEC.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_EQ.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_GE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_GT.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_INC.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_LE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_LT.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_NE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_NEG.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_OR.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_PTR.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.OP_SHIFT_LEFT.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.PLUS.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.REAL_LITERAL.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.SEMICOLON.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.STAR.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.STRING_LITERAL.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.TILDE.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.TokenType.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.parse.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.read_token.html
/usr/share/devhelp/books/GCalc-2/GCalc.Parser.token_to_string.html
/usr/share/devhelp/books/GCalc-2/GCalc.ParserError.INVALID_EXPRESSION_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.ParserError.INVALID_TOKEN_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.ParserError.html
/usr/share/devhelp/books/GCalc-2/GCalc.Plus.Plus.html
/usr/share/devhelp/books/GCalc-2/GCalc.Plus.html
/usr/share/devhelp/books/GCalc-2/GCalc.Polynomial.Polynomial.html
/usr/share/devhelp/books/GCalc-2/GCalc.Polynomial.html
/usr/share/devhelp/books/GCalc-2/GCalc.Pow.Pow.html
/usr/share/devhelp/books/GCalc-2/GCalc.Pow.html
/usr/share/devhelp/books/GCalc-2/GCalc.Result.Result.html
/usr/share/devhelp/books/GCalc-2/GCalc.Result.html
/usr/share/devhelp/books/GCalc-2/GCalc.Solver.Solver.html
/usr/share/devhelp/books/GCalc-2/GCalc.Solver.add_expression.html
/usr/share/devhelp/books/GCalc-2/GCalc.Solver.equation_manager.html
/usr/share/devhelp/books/GCalc-2/GCalc.Solver.html
/usr/share/devhelp/books/GCalc-2/GCalc.Solver.solve.html
/usr/share/devhelp/books/GCalc-2/GCalc.SolverError.EXPRESSION_ERROR.html
/usr/share/devhelp/books/GCalc-2/GCalc.SolverError.html
/usr/share/devhelp/books/GCalc-2/GCalc.Term.Term.html
/usr/share/devhelp/books/GCalc-2/GCalc.Term.html
/usr/share/devhelp/books/GCalc-2/GCalc.TermError.EVALUATION_FAIL.html
/usr/share/devhelp/books/GCalc-2/GCalc.TermError.INVALID_OPERATOR.html
/usr/share/devhelp/books/GCalc-2/GCalc.TermError.html
/usr/share/devhelp/books/GCalc-2/GCalc.Variable.html
/usr/share/devhelp/books/GCalc-2/GCalc.Variable.name.html
/usr/share/devhelp/books/GCalc-2/GCalc.VariableError.EVALUATION_FAIL.html
/usr/share/devhelp/books/GCalc-2/GCalc.VariableError.INVALID_EXPRESSION_DEFINITION.html
/usr/share/devhelp/books/GCalc-2/GCalc.VariableError.INVALID_PARENT.html
/usr/share/devhelp/books/GCalc-2/GCalc.VariableError.html
/usr/share/devhelp/books/GCalc-2/GCalc.html
/usr/share/devhelp/books/GCalc-2/abstractclass.svg
/usr/share/devhelp/books/GCalc-2/abstractmethod.svg
/usr/share/devhelp/books/GCalc-2/abstractproperty.svg
/usr/share/devhelp/books/GCalc-2/class.svg
/usr/share/devhelp/books/GCalc-2/coll_close.svg
/usr/share/devhelp/books/GCalc-2/coll_open.svg
/usr/share/devhelp/books/GCalc-2/constant.svg
/usr/share/devhelp/books/GCalc-2/constructor.svg
/usr/share/devhelp/books/GCalc-2/delegate.svg
/usr/share/devhelp/books/GCalc-2/devhelpstyle.css
/usr/share/devhelp/books/GCalc-2/enum.svg
/usr/share/devhelp/books/GCalc-2/enumvalue.svg
/usr/share/devhelp/books/GCalc-2/errorcode.svg
/usr/share/devhelp/books/GCalc-2/errordomain.svg
/usr/share/devhelp/books/GCalc-2/field.svg
/usr/share/devhelp/books/GCalc-2/index.htm
/usr/share/devhelp/books/GCalc-2/interface.svg
/usr/share/devhelp/books/GCalc-2/method.svg
/usr/share/devhelp/books/GCalc-2/namespace.svg
/usr/share/devhelp/books/GCalc-2/package.svg
/usr/share/devhelp/books/GCalc-2/packages.svg
/usr/share/devhelp/books/GCalc-2/property.svg
/usr/share/devhelp/books/GCalc-2/scripts.js
/usr/share/devhelp/books/GCalc-2/signal.svg
/usr/share/devhelp/books/GCalc-2/staticmethod.svg
/usr/share/devhelp/books/GCalc-2/struct.svg
/usr/share/devhelp/books/GCalc-2/style.css
/usr/share/devhelp/books/GCalc-2/tip.svg
/usr/share/devhelp/books/GCalc-2/virtualmethod.svg
/usr/share/devhelp/books/GCalc-2/virtualproperty.svg
/usr/share/devhelp/books/GCalc-2/warning.svg
/usr/share/devhelp/books/GCalc-2/wikistyle.css
/usr/share/devhelp/books/GCi-1/GCi-1.devhelp2
/usr/share/devhelp/books/GCi-1/GCi.EntryController.EntryController.for_entry.html
/usr/share/devhelp/books/GCi-1/GCi.EntryController.EntryController.html
/usr/share/devhelp/books/GCi-1/GCi.EntryController.entry.html
/usr/share/devhelp/books/GCi-1/GCi.EntryController.html
/usr/share/devhelp/books/GCi-1/GCi.html
/usr/share/devhelp/books/GCi-1/abstractclass.svg
/usr/share/devhelp/books/GCi-1/abstractmethod.svg
/usr/share/devhelp/books/GCi-1/abstractproperty.svg
/usr/share/devhelp/books/GCi-1/class.svg
/usr/share/devhelp/books/GCi-1/coll_close.svg
/usr/share/devhelp/books/GCi-1/coll_open.svg
/usr/share/devhelp/books/GCi-1/constant.svg
/usr/share/devhelp/books/GCi-1/constructor.svg
/usr/share/devhelp/books/GCi-1/delegate.svg
/usr/share/devhelp/books/GCi-1/devhelpstyle.css
/usr/share/devhelp/books/GCi-1/enum.svg
/usr/share/devhelp/books/GCi-1/enumvalue.svg
/usr/share/devhelp/books/GCi-1/errorcode.svg
/usr/share/devhelp/books/GCi-1/errordomain.svg
/usr/share/devhelp/books/GCi-1/field.svg
/usr/share/devhelp/books/GCi-1/index.htm
/usr/share/devhelp/books/GCi-1/interface.svg
/usr/share/devhelp/books/GCi-1/method.svg
/usr/share/devhelp/books/GCi-1/namespace.svg
/usr/share/devhelp/books/GCi-1/package.svg
/usr/share/devhelp/books/GCi-1/packages.svg
/usr/share/devhelp/books/GCi-1/property.svg
/usr/share/devhelp/books/GCi-1/scripts.js
/usr/share/devhelp/books/GCi-1/signal.svg
/usr/share/devhelp/books/GCi-1/staticmethod.svg
/usr/share/devhelp/books/GCi-1/struct.svg
/usr/share/devhelp/books/GCi-1/style.css
/usr/share/devhelp/books/GCi-1/tip.svg
/usr/share/devhelp/books/GCi-1/virtualmethod.svg
/usr/share/devhelp/books/GCi-1/virtualproperty.svg
/usr/share/devhelp/books/GCi-1/warning.svg
/usr/share/devhelp/books/GCi-1/wikistyle.css
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.calculator.gschema.xml
/usr/share/gnome-shell/search-providers/org.gnome.Calculator-search-provider.ini
/usr/share/icons/hicolor/scalable/apps/org.gnome.Calculator.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Calculator-symbolic.svg
/usr/share/metainfo/org.gnome.Calculator.appdata.xml
/usr/share/vala/vapi/gcalc-2.deps
/usr/share/vala/vapi/gcalc-2.vapi
/usr/share/vala/vapi/gci-1.deps
/usr/share/vala/vapi/gci-1.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gcalc-2/gcalc/gcalc.h
/usr/include/gci-2/gci/gci.h
/usr/lib64/libgcalc-2.so
/usr/lib64/libgci-1.so
/usr/lib64/pkgconfig/gcalc-2.pc
/usr/lib64/pkgconfig/gci-1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gnome-calculator/absolute.page
/usr/share/help/C/gnome-calculator/base.page
/usr/share/help/C/gnome-calculator/boolean.page
/usr/share/help/C/gnome-calculator/complex.page
/usr/share/help/C/gnome-calculator/conv-base.page
/usr/share/help/C/gnome-calculator/conv-character.page
/usr/share/help/C/gnome-calculator/conv-currency.page
/usr/share/help/C/gnome-calculator/conv-length.page
/usr/share/help/C/gnome-calculator/conv-time.page
/usr/share/help/C/gnome-calculator/conv-weight.page
/usr/share/help/C/gnome-calculator/equation.page
/usr/share/help/C/gnome-calculator/factorial.page
/usr/share/help/C/gnome-calculator/factorize.page
/usr/share/help/C/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/C/gnome-calculator/financial.page
/usr/share/help/C/gnome-calculator/functions.page
/usr/share/help/C/gnome-calculator/history.page
/usr/share/help/C/gnome-calculator/index.page
/usr/share/help/C/gnome-calculator/keyboard.page
/usr/share/help/C/gnome-calculator/legal.xml
/usr/share/help/C/gnome-calculator/logarithm.page
/usr/share/help/C/gnome-calculator/modulus.page
/usr/share/help/C/gnome-calculator/mouse.page
/usr/share/help/C/gnome-calculator/number-display.page
/usr/share/help/C/gnome-calculator/percentage.page
/usr/share/help/C/gnome-calculator/power.page
/usr/share/help/C/gnome-calculator/scientific.page
/usr/share/help/C/gnome-calculator/superscript.page
/usr/share/help/C/gnome-calculator/trigonometry.page
/usr/share/help/C/gnome-calculator/variables.page
/usr/share/help/bg/gnome-calculator/absolute.page
/usr/share/help/bg/gnome-calculator/base.page
/usr/share/help/bg/gnome-calculator/boolean.page
/usr/share/help/bg/gnome-calculator/complex.page
/usr/share/help/bg/gnome-calculator/conv-base.page
/usr/share/help/bg/gnome-calculator/conv-character.page
/usr/share/help/bg/gnome-calculator/conv-currency.page
/usr/share/help/bg/gnome-calculator/conv-length.page
/usr/share/help/bg/gnome-calculator/conv-time.page
/usr/share/help/bg/gnome-calculator/conv-weight.page
/usr/share/help/bg/gnome-calculator/equation.page
/usr/share/help/bg/gnome-calculator/factorial.page
/usr/share/help/bg/gnome-calculator/factorize.page
/usr/share/help/bg/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/bg/gnome-calculator/financial.page
/usr/share/help/bg/gnome-calculator/functions.page
/usr/share/help/bg/gnome-calculator/history.page
/usr/share/help/bg/gnome-calculator/index.page
/usr/share/help/bg/gnome-calculator/keyboard.page
/usr/share/help/bg/gnome-calculator/legal.xml
/usr/share/help/bg/gnome-calculator/logarithm.page
/usr/share/help/bg/gnome-calculator/modulus.page
/usr/share/help/bg/gnome-calculator/mouse.page
/usr/share/help/bg/gnome-calculator/number-display.page
/usr/share/help/bg/gnome-calculator/percentage.page
/usr/share/help/bg/gnome-calculator/power.page
/usr/share/help/bg/gnome-calculator/scientific.page
/usr/share/help/bg/gnome-calculator/superscript.page
/usr/share/help/bg/gnome-calculator/trigonometry.page
/usr/share/help/bg/gnome-calculator/variables.page
/usr/share/help/ca/gnome-calculator/absolute.page
/usr/share/help/ca/gnome-calculator/base.page
/usr/share/help/ca/gnome-calculator/boolean.page
/usr/share/help/ca/gnome-calculator/complex.page
/usr/share/help/ca/gnome-calculator/conv-base.page
/usr/share/help/ca/gnome-calculator/conv-character.page
/usr/share/help/ca/gnome-calculator/conv-currency.page
/usr/share/help/ca/gnome-calculator/conv-length.page
/usr/share/help/ca/gnome-calculator/conv-time.page
/usr/share/help/ca/gnome-calculator/conv-weight.page
/usr/share/help/ca/gnome-calculator/equation.page
/usr/share/help/ca/gnome-calculator/factorial.page
/usr/share/help/ca/gnome-calculator/factorize.page
/usr/share/help/ca/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/ca/gnome-calculator/financial.page
/usr/share/help/ca/gnome-calculator/functions.page
/usr/share/help/ca/gnome-calculator/history.page
/usr/share/help/ca/gnome-calculator/index.page
/usr/share/help/ca/gnome-calculator/keyboard.page
/usr/share/help/ca/gnome-calculator/legal.xml
/usr/share/help/ca/gnome-calculator/logarithm.page
/usr/share/help/ca/gnome-calculator/modulus.page
/usr/share/help/ca/gnome-calculator/mouse.page
/usr/share/help/ca/gnome-calculator/number-display.page
/usr/share/help/ca/gnome-calculator/percentage.page
/usr/share/help/ca/gnome-calculator/power.page
/usr/share/help/ca/gnome-calculator/scientific.page
/usr/share/help/ca/gnome-calculator/superscript.page
/usr/share/help/ca/gnome-calculator/trigonometry.page
/usr/share/help/ca/gnome-calculator/variables.page
/usr/share/help/cs/gnome-calculator/absolute.page
/usr/share/help/cs/gnome-calculator/base.page
/usr/share/help/cs/gnome-calculator/boolean.page
/usr/share/help/cs/gnome-calculator/complex.page
/usr/share/help/cs/gnome-calculator/conv-base.page
/usr/share/help/cs/gnome-calculator/conv-character.page
/usr/share/help/cs/gnome-calculator/conv-currency.page
/usr/share/help/cs/gnome-calculator/conv-length.page
/usr/share/help/cs/gnome-calculator/conv-time.page
/usr/share/help/cs/gnome-calculator/conv-weight.page
/usr/share/help/cs/gnome-calculator/equation.page
/usr/share/help/cs/gnome-calculator/factorial.page
/usr/share/help/cs/gnome-calculator/factorize.page
/usr/share/help/cs/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/cs/gnome-calculator/financial.page
/usr/share/help/cs/gnome-calculator/functions.page
/usr/share/help/cs/gnome-calculator/history.page
/usr/share/help/cs/gnome-calculator/index.page
/usr/share/help/cs/gnome-calculator/keyboard.page
/usr/share/help/cs/gnome-calculator/legal.xml
/usr/share/help/cs/gnome-calculator/logarithm.page
/usr/share/help/cs/gnome-calculator/modulus.page
/usr/share/help/cs/gnome-calculator/mouse.page
/usr/share/help/cs/gnome-calculator/number-display.page
/usr/share/help/cs/gnome-calculator/percentage.page
/usr/share/help/cs/gnome-calculator/power.page
/usr/share/help/cs/gnome-calculator/scientific.page
/usr/share/help/cs/gnome-calculator/superscript.page
/usr/share/help/cs/gnome-calculator/trigonometry.page
/usr/share/help/cs/gnome-calculator/variables.page
/usr/share/help/da/gnome-calculator/absolute.page
/usr/share/help/da/gnome-calculator/base.page
/usr/share/help/da/gnome-calculator/boolean.page
/usr/share/help/da/gnome-calculator/complex.page
/usr/share/help/da/gnome-calculator/conv-base.page
/usr/share/help/da/gnome-calculator/conv-character.page
/usr/share/help/da/gnome-calculator/conv-currency.page
/usr/share/help/da/gnome-calculator/conv-length.page
/usr/share/help/da/gnome-calculator/conv-time.page
/usr/share/help/da/gnome-calculator/conv-weight.page
/usr/share/help/da/gnome-calculator/equation.page
/usr/share/help/da/gnome-calculator/factorial.page
/usr/share/help/da/gnome-calculator/factorize.page
/usr/share/help/da/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/da/gnome-calculator/financial.page
/usr/share/help/da/gnome-calculator/functions.page
/usr/share/help/da/gnome-calculator/history.page
/usr/share/help/da/gnome-calculator/index.page
/usr/share/help/da/gnome-calculator/keyboard.page
/usr/share/help/da/gnome-calculator/legal.xml
/usr/share/help/da/gnome-calculator/logarithm.page
/usr/share/help/da/gnome-calculator/modulus.page
/usr/share/help/da/gnome-calculator/mouse.page
/usr/share/help/da/gnome-calculator/number-display.page
/usr/share/help/da/gnome-calculator/percentage.page
/usr/share/help/da/gnome-calculator/power.page
/usr/share/help/da/gnome-calculator/scientific.page
/usr/share/help/da/gnome-calculator/superscript.page
/usr/share/help/da/gnome-calculator/trigonometry.page
/usr/share/help/da/gnome-calculator/variables.page
/usr/share/help/de/gnome-calculator/absolute.page
/usr/share/help/de/gnome-calculator/base.page
/usr/share/help/de/gnome-calculator/boolean.page
/usr/share/help/de/gnome-calculator/complex.page
/usr/share/help/de/gnome-calculator/conv-base.page
/usr/share/help/de/gnome-calculator/conv-character.page
/usr/share/help/de/gnome-calculator/conv-currency.page
/usr/share/help/de/gnome-calculator/conv-length.page
/usr/share/help/de/gnome-calculator/conv-time.page
/usr/share/help/de/gnome-calculator/conv-weight.page
/usr/share/help/de/gnome-calculator/equation.page
/usr/share/help/de/gnome-calculator/factorial.page
/usr/share/help/de/gnome-calculator/factorize.page
/usr/share/help/de/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/de/gnome-calculator/financial.page
/usr/share/help/de/gnome-calculator/functions.page
/usr/share/help/de/gnome-calculator/history.page
/usr/share/help/de/gnome-calculator/index.page
/usr/share/help/de/gnome-calculator/keyboard.page
/usr/share/help/de/gnome-calculator/legal.xml
/usr/share/help/de/gnome-calculator/logarithm.page
/usr/share/help/de/gnome-calculator/modulus.page
/usr/share/help/de/gnome-calculator/mouse.page
/usr/share/help/de/gnome-calculator/number-display.page
/usr/share/help/de/gnome-calculator/percentage.page
/usr/share/help/de/gnome-calculator/power.page
/usr/share/help/de/gnome-calculator/scientific.page
/usr/share/help/de/gnome-calculator/superscript.page
/usr/share/help/de/gnome-calculator/trigonometry.page
/usr/share/help/de/gnome-calculator/variables.page
/usr/share/help/el/gnome-calculator/absolute.page
/usr/share/help/el/gnome-calculator/base.page
/usr/share/help/el/gnome-calculator/boolean.page
/usr/share/help/el/gnome-calculator/complex.page
/usr/share/help/el/gnome-calculator/conv-base.page
/usr/share/help/el/gnome-calculator/conv-character.page
/usr/share/help/el/gnome-calculator/conv-currency.page
/usr/share/help/el/gnome-calculator/conv-length.page
/usr/share/help/el/gnome-calculator/conv-time.page
/usr/share/help/el/gnome-calculator/conv-weight.page
/usr/share/help/el/gnome-calculator/equation.page
/usr/share/help/el/gnome-calculator/factorial.page
/usr/share/help/el/gnome-calculator/factorize.page
/usr/share/help/el/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/el/gnome-calculator/financial.page
/usr/share/help/el/gnome-calculator/functions.page
/usr/share/help/el/gnome-calculator/history.page
/usr/share/help/el/gnome-calculator/index.page
/usr/share/help/el/gnome-calculator/keyboard.page
/usr/share/help/el/gnome-calculator/legal.xml
/usr/share/help/el/gnome-calculator/logarithm.page
/usr/share/help/el/gnome-calculator/modulus.page
/usr/share/help/el/gnome-calculator/mouse.page
/usr/share/help/el/gnome-calculator/number-display.page
/usr/share/help/el/gnome-calculator/percentage.page
/usr/share/help/el/gnome-calculator/power.page
/usr/share/help/el/gnome-calculator/scientific.page
/usr/share/help/el/gnome-calculator/superscript.page
/usr/share/help/el/gnome-calculator/trigonometry.page
/usr/share/help/el/gnome-calculator/variables.page
/usr/share/help/es/gnome-calculator/absolute.page
/usr/share/help/es/gnome-calculator/base.page
/usr/share/help/es/gnome-calculator/boolean.page
/usr/share/help/es/gnome-calculator/complex.page
/usr/share/help/es/gnome-calculator/conv-base.page
/usr/share/help/es/gnome-calculator/conv-character.page
/usr/share/help/es/gnome-calculator/conv-currency.page
/usr/share/help/es/gnome-calculator/conv-length.page
/usr/share/help/es/gnome-calculator/conv-time.page
/usr/share/help/es/gnome-calculator/conv-weight.page
/usr/share/help/es/gnome-calculator/equation.page
/usr/share/help/es/gnome-calculator/factorial.page
/usr/share/help/es/gnome-calculator/factorize.page
/usr/share/help/es/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/es/gnome-calculator/financial.page
/usr/share/help/es/gnome-calculator/functions.page
/usr/share/help/es/gnome-calculator/history.page
/usr/share/help/es/gnome-calculator/index.page
/usr/share/help/es/gnome-calculator/keyboard.page
/usr/share/help/es/gnome-calculator/legal.xml
/usr/share/help/es/gnome-calculator/logarithm.page
/usr/share/help/es/gnome-calculator/modulus.page
/usr/share/help/es/gnome-calculator/mouse.page
/usr/share/help/es/gnome-calculator/number-display.page
/usr/share/help/es/gnome-calculator/percentage.page
/usr/share/help/es/gnome-calculator/power.page
/usr/share/help/es/gnome-calculator/scientific.page
/usr/share/help/es/gnome-calculator/superscript.page
/usr/share/help/es/gnome-calculator/trigonometry.page
/usr/share/help/es/gnome-calculator/variables.page
/usr/share/help/eu/gnome-calculator/absolute.page
/usr/share/help/eu/gnome-calculator/base.page
/usr/share/help/eu/gnome-calculator/boolean.page
/usr/share/help/eu/gnome-calculator/complex.page
/usr/share/help/eu/gnome-calculator/conv-base.page
/usr/share/help/eu/gnome-calculator/conv-character.page
/usr/share/help/eu/gnome-calculator/conv-currency.page
/usr/share/help/eu/gnome-calculator/conv-length.page
/usr/share/help/eu/gnome-calculator/conv-time.page
/usr/share/help/eu/gnome-calculator/conv-weight.page
/usr/share/help/eu/gnome-calculator/equation.page
/usr/share/help/eu/gnome-calculator/factorial.page
/usr/share/help/eu/gnome-calculator/factorize.page
/usr/share/help/eu/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/eu/gnome-calculator/financial.page
/usr/share/help/eu/gnome-calculator/functions.page
/usr/share/help/eu/gnome-calculator/history.page
/usr/share/help/eu/gnome-calculator/index.page
/usr/share/help/eu/gnome-calculator/keyboard.page
/usr/share/help/eu/gnome-calculator/legal.xml
/usr/share/help/eu/gnome-calculator/logarithm.page
/usr/share/help/eu/gnome-calculator/modulus.page
/usr/share/help/eu/gnome-calculator/mouse.page
/usr/share/help/eu/gnome-calculator/number-display.page
/usr/share/help/eu/gnome-calculator/percentage.page
/usr/share/help/eu/gnome-calculator/power.page
/usr/share/help/eu/gnome-calculator/scientific.page
/usr/share/help/eu/gnome-calculator/superscript.page
/usr/share/help/eu/gnome-calculator/trigonometry.page
/usr/share/help/eu/gnome-calculator/variables.page
/usr/share/help/fi/gnome-calculator/absolute.page
/usr/share/help/fi/gnome-calculator/base.page
/usr/share/help/fi/gnome-calculator/boolean.page
/usr/share/help/fi/gnome-calculator/complex.page
/usr/share/help/fi/gnome-calculator/conv-base.page
/usr/share/help/fi/gnome-calculator/conv-character.page
/usr/share/help/fi/gnome-calculator/conv-currency.page
/usr/share/help/fi/gnome-calculator/conv-length.page
/usr/share/help/fi/gnome-calculator/conv-time.page
/usr/share/help/fi/gnome-calculator/conv-weight.page
/usr/share/help/fi/gnome-calculator/equation.page
/usr/share/help/fi/gnome-calculator/factorial.page
/usr/share/help/fi/gnome-calculator/factorize.page
/usr/share/help/fi/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/fi/gnome-calculator/financial.page
/usr/share/help/fi/gnome-calculator/functions.page
/usr/share/help/fi/gnome-calculator/history.page
/usr/share/help/fi/gnome-calculator/index.page
/usr/share/help/fi/gnome-calculator/keyboard.page
/usr/share/help/fi/gnome-calculator/legal.xml
/usr/share/help/fi/gnome-calculator/logarithm.page
/usr/share/help/fi/gnome-calculator/modulus.page
/usr/share/help/fi/gnome-calculator/mouse.page
/usr/share/help/fi/gnome-calculator/number-display.page
/usr/share/help/fi/gnome-calculator/percentage.page
/usr/share/help/fi/gnome-calculator/power.page
/usr/share/help/fi/gnome-calculator/scientific.page
/usr/share/help/fi/gnome-calculator/superscript.page
/usr/share/help/fi/gnome-calculator/trigonometry.page
/usr/share/help/fi/gnome-calculator/variables.page
/usr/share/help/fr/gnome-calculator/absolute.page
/usr/share/help/fr/gnome-calculator/base.page
/usr/share/help/fr/gnome-calculator/boolean.page
/usr/share/help/fr/gnome-calculator/complex.page
/usr/share/help/fr/gnome-calculator/conv-base.page
/usr/share/help/fr/gnome-calculator/conv-character.page
/usr/share/help/fr/gnome-calculator/conv-currency.page
/usr/share/help/fr/gnome-calculator/conv-length.page
/usr/share/help/fr/gnome-calculator/conv-time.page
/usr/share/help/fr/gnome-calculator/conv-weight.page
/usr/share/help/fr/gnome-calculator/equation.page
/usr/share/help/fr/gnome-calculator/factorial.page
/usr/share/help/fr/gnome-calculator/factorize.page
/usr/share/help/fr/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/fr/gnome-calculator/financial.page
/usr/share/help/fr/gnome-calculator/functions.page
/usr/share/help/fr/gnome-calculator/history.page
/usr/share/help/fr/gnome-calculator/index.page
/usr/share/help/fr/gnome-calculator/keyboard.page
/usr/share/help/fr/gnome-calculator/legal.xml
/usr/share/help/fr/gnome-calculator/logarithm.page
/usr/share/help/fr/gnome-calculator/modulus.page
/usr/share/help/fr/gnome-calculator/mouse.page
/usr/share/help/fr/gnome-calculator/number-display.page
/usr/share/help/fr/gnome-calculator/percentage.page
/usr/share/help/fr/gnome-calculator/power.page
/usr/share/help/fr/gnome-calculator/scientific.page
/usr/share/help/fr/gnome-calculator/superscript.page
/usr/share/help/fr/gnome-calculator/trigonometry.page
/usr/share/help/fr/gnome-calculator/variables.page
/usr/share/help/gl/gnome-calculator/absolute.page
/usr/share/help/gl/gnome-calculator/base.page
/usr/share/help/gl/gnome-calculator/boolean.page
/usr/share/help/gl/gnome-calculator/complex.page
/usr/share/help/gl/gnome-calculator/conv-base.page
/usr/share/help/gl/gnome-calculator/conv-character.page
/usr/share/help/gl/gnome-calculator/conv-currency.page
/usr/share/help/gl/gnome-calculator/conv-length.page
/usr/share/help/gl/gnome-calculator/conv-time.page
/usr/share/help/gl/gnome-calculator/conv-weight.page
/usr/share/help/gl/gnome-calculator/equation.page
/usr/share/help/gl/gnome-calculator/factorial.page
/usr/share/help/gl/gnome-calculator/factorize.page
/usr/share/help/gl/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/gl/gnome-calculator/financial.page
/usr/share/help/gl/gnome-calculator/functions.page
/usr/share/help/gl/gnome-calculator/history.page
/usr/share/help/gl/gnome-calculator/index.page
/usr/share/help/gl/gnome-calculator/keyboard.page
/usr/share/help/gl/gnome-calculator/legal.xml
/usr/share/help/gl/gnome-calculator/logarithm.page
/usr/share/help/gl/gnome-calculator/modulus.page
/usr/share/help/gl/gnome-calculator/mouse.page
/usr/share/help/gl/gnome-calculator/number-display.page
/usr/share/help/gl/gnome-calculator/percentage.page
/usr/share/help/gl/gnome-calculator/power.page
/usr/share/help/gl/gnome-calculator/scientific.page
/usr/share/help/gl/gnome-calculator/superscript.page
/usr/share/help/gl/gnome-calculator/trigonometry.page
/usr/share/help/gl/gnome-calculator/variables.page
/usr/share/help/hu/gnome-calculator/absolute.page
/usr/share/help/hu/gnome-calculator/base.page
/usr/share/help/hu/gnome-calculator/boolean.page
/usr/share/help/hu/gnome-calculator/complex.page
/usr/share/help/hu/gnome-calculator/conv-base.page
/usr/share/help/hu/gnome-calculator/conv-character.page
/usr/share/help/hu/gnome-calculator/conv-currency.page
/usr/share/help/hu/gnome-calculator/conv-length.page
/usr/share/help/hu/gnome-calculator/conv-time.page
/usr/share/help/hu/gnome-calculator/conv-weight.page
/usr/share/help/hu/gnome-calculator/equation.page
/usr/share/help/hu/gnome-calculator/factorial.page
/usr/share/help/hu/gnome-calculator/factorize.page
/usr/share/help/hu/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/hu/gnome-calculator/financial.page
/usr/share/help/hu/gnome-calculator/functions.page
/usr/share/help/hu/gnome-calculator/history.page
/usr/share/help/hu/gnome-calculator/index.page
/usr/share/help/hu/gnome-calculator/keyboard.page
/usr/share/help/hu/gnome-calculator/legal.xml
/usr/share/help/hu/gnome-calculator/logarithm.page
/usr/share/help/hu/gnome-calculator/modulus.page
/usr/share/help/hu/gnome-calculator/mouse.page
/usr/share/help/hu/gnome-calculator/number-display.page
/usr/share/help/hu/gnome-calculator/percentage.page
/usr/share/help/hu/gnome-calculator/power.page
/usr/share/help/hu/gnome-calculator/scientific.page
/usr/share/help/hu/gnome-calculator/superscript.page
/usr/share/help/hu/gnome-calculator/trigonometry.page
/usr/share/help/hu/gnome-calculator/variables.page
/usr/share/help/id/gnome-calculator/absolute.page
/usr/share/help/id/gnome-calculator/base.page
/usr/share/help/id/gnome-calculator/boolean.page
/usr/share/help/id/gnome-calculator/complex.page
/usr/share/help/id/gnome-calculator/conv-base.page
/usr/share/help/id/gnome-calculator/conv-character.page
/usr/share/help/id/gnome-calculator/conv-currency.page
/usr/share/help/id/gnome-calculator/conv-length.page
/usr/share/help/id/gnome-calculator/conv-time.page
/usr/share/help/id/gnome-calculator/conv-weight.page
/usr/share/help/id/gnome-calculator/equation.page
/usr/share/help/id/gnome-calculator/factorial.page
/usr/share/help/id/gnome-calculator/factorize.page
/usr/share/help/id/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/id/gnome-calculator/financial.page
/usr/share/help/id/gnome-calculator/functions.page
/usr/share/help/id/gnome-calculator/history.page
/usr/share/help/id/gnome-calculator/index.page
/usr/share/help/id/gnome-calculator/keyboard.page
/usr/share/help/id/gnome-calculator/legal.xml
/usr/share/help/id/gnome-calculator/logarithm.page
/usr/share/help/id/gnome-calculator/modulus.page
/usr/share/help/id/gnome-calculator/mouse.page
/usr/share/help/id/gnome-calculator/number-display.page
/usr/share/help/id/gnome-calculator/percentage.page
/usr/share/help/id/gnome-calculator/power.page
/usr/share/help/id/gnome-calculator/scientific.page
/usr/share/help/id/gnome-calculator/superscript.page
/usr/share/help/id/gnome-calculator/trigonometry.page
/usr/share/help/id/gnome-calculator/variables.page
/usr/share/help/it/gnome-calculator/absolute.page
/usr/share/help/it/gnome-calculator/base.page
/usr/share/help/it/gnome-calculator/boolean.page
/usr/share/help/it/gnome-calculator/complex.page
/usr/share/help/it/gnome-calculator/conv-base.page
/usr/share/help/it/gnome-calculator/conv-character.page
/usr/share/help/it/gnome-calculator/conv-currency.page
/usr/share/help/it/gnome-calculator/conv-length.page
/usr/share/help/it/gnome-calculator/conv-time.page
/usr/share/help/it/gnome-calculator/conv-weight.page
/usr/share/help/it/gnome-calculator/equation.page
/usr/share/help/it/gnome-calculator/factorial.page
/usr/share/help/it/gnome-calculator/factorize.page
/usr/share/help/it/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/it/gnome-calculator/financial.page
/usr/share/help/it/gnome-calculator/functions.page
/usr/share/help/it/gnome-calculator/history.page
/usr/share/help/it/gnome-calculator/index.page
/usr/share/help/it/gnome-calculator/keyboard.page
/usr/share/help/it/gnome-calculator/legal.xml
/usr/share/help/it/gnome-calculator/logarithm.page
/usr/share/help/it/gnome-calculator/modulus.page
/usr/share/help/it/gnome-calculator/mouse.page
/usr/share/help/it/gnome-calculator/number-display.page
/usr/share/help/it/gnome-calculator/percentage.page
/usr/share/help/it/gnome-calculator/power.page
/usr/share/help/it/gnome-calculator/scientific.page
/usr/share/help/it/gnome-calculator/superscript.page
/usr/share/help/it/gnome-calculator/trigonometry.page
/usr/share/help/it/gnome-calculator/variables.page
/usr/share/help/ja/gnome-calculator/absolute.page
/usr/share/help/ja/gnome-calculator/base.page
/usr/share/help/ja/gnome-calculator/boolean.page
/usr/share/help/ja/gnome-calculator/complex.page
/usr/share/help/ja/gnome-calculator/conv-base.page
/usr/share/help/ja/gnome-calculator/conv-character.page
/usr/share/help/ja/gnome-calculator/conv-currency.page
/usr/share/help/ja/gnome-calculator/conv-length.page
/usr/share/help/ja/gnome-calculator/conv-time.page
/usr/share/help/ja/gnome-calculator/conv-weight.page
/usr/share/help/ja/gnome-calculator/equation.page
/usr/share/help/ja/gnome-calculator/factorial.page
/usr/share/help/ja/gnome-calculator/factorize.page
/usr/share/help/ja/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/ja/gnome-calculator/financial.page
/usr/share/help/ja/gnome-calculator/functions.page
/usr/share/help/ja/gnome-calculator/history.page
/usr/share/help/ja/gnome-calculator/index.page
/usr/share/help/ja/gnome-calculator/keyboard.page
/usr/share/help/ja/gnome-calculator/legal.xml
/usr/share/help/ja/gnome-calculator/logarithm.page
/usr/share/help/ja/gnome-calculator/modulus.page
/usr/share/help/ja/gnome-calculator/mouse.page
/usr/share/help/ja/gnome-calculator/number-display.page
/usr/share/help/ja/gnome-calculator/percentage.page
/usr/share/help/ja/gnome-calculator/power.page
/usr/share/help/ja/gnome-calculator/scientific.page
/usr/share/help/ja/gnome-calculator/superscript.page
/usr/share/help/ja/gnome-calculator/trigonometry.page
/usr/share/help/ja/gnome-calculator/variables.page
/usr/share/help/ko/gnome-calculator/absolute.page
/usr/share/help/ko/gnome-calculator/base.page
/usr/share/help/ko/gnome-calculator/boolean.page
/usr/share/help/ko/gnome-calculator/complex.page
/usr/share/help/ko/gnome-calculator/conv-base.page
/usr/share/help/ko/gnome-calculator/conv-character.page
/usr/share/help/ko/gnome-calculator/conv-currency.page
/usr/share/help/ko/gnome-calculator/conv-length.page
/usr/share/help/ko/gnome-calculator/conv-time.page
/usr/share/help/ko/gnome-calculator/conv-weight.page
/usr/share/help/ko/gnome-calculator/equation.page
/usr/share/help/ko/gnome-calculator/factorial.page
/usr/share/help/ko/gnome-calculator/factorize.page
/usr/share/help/ko/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/ko/gnome-calculator/financial.page
/usr/share/help/ko/gnome-calculator/functions.page
/usr/share/help/ko/gnome-calculator/history.page
/usr/share/help/ko/gnome-calculator/index.page
/usr/share/help/ko/gnome-calculator/keyboard.page
/usr/share/help/ko/gnome-calculator/legal.xml
/usr/share/help/ko/gnome-calculator/logarithm.page
/usr/share/help/ko/gnome-calculator/modulus.page
/usr/share/help/ko/gnome-calculator/mouse.page
/usr/share/help/ko/gnome-calculator/number-display.page
/usr/share/help/ko/gnome-calculator/percentage.page
/usr/share/help/ko/gnome-calculator/power.page
/usr/share/help/ko/gnome-calculator/scientific.page
/usr/share/help/ko/gnome-calculator/superscript.page
/usr/share/help/ko/gnome-calculator/trigonometry.page
/usr/share/help/ko/gnome-calculator/variables.page
/usr/share/help/lv/gnome-calculator/absolute.page
/usr/share/help/lv/gnome-calculator/base.page
/usr/share/help/lv/gnome-calculator/boolean.page
/usr/share/help/lv/gnome-calculator/complex.page
/usr/share/help/lv/gnome-calculator/conv-base.page
/usr/share/help/lv/gnome-calculator/conv-character.page
/usr/share/help/lv/gnome-calculator/conv-currency.page
/usr/share/help/lv/gnome-calculator/conv-length.page
/usr/share/help/lv/gnome-calculator/conv-time.page
/usr/share/help/lv/gnome-calculator/conv-weight.page
/usr/share/help/lv/gnome-calculator/equation.page
/usr/share/help/lv/gnome-calculator/factorial.page
/usr/share/help/lv/gnome-calculator/factorize.page
/usr/share/help/lv/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/lv/gnome-calculator/financial.page
/usr/share/help/lv/gnome-calculator/functions.page
/usr/share/help/lv/gnome-calculator/history.page
/usr/share/help/lv/gnome-calculator/index.page
/usr/share/help/lv/gnome-calculator/keyboard.page
/usr/share/help/lv/gnome-calculator/legal.xml
/usr/share/help/lv/gnome-calculator/logarithm.page
/usr/share/help/lv/gnome-calculator/modulus.page
/usr/share/help/lv/gnome-calculator/mouse.page
/usr/share/help/lv/gnome-calculator/number-display.page
/usr/share/help/lv/gnome-calculator/percentage.page
/usr/share/help/lv/gnome-calculator/power.page
/usr/share/help/lv/gnome-calculator/scientific.page
/usr/share/help/lv/gnome-calculator/superscript.page
/usr/share/help/lv/gnome-calculator/trigonometry.page
/usr/share/help/lv/gnome-calculator/variables.page
/usr/share/help/oc/gnome-calculator/absolute.page
/usr/share/help/oc/gnome-calculator/base.page
/usr/share/help/oc/gnome-calculator/boolean.page
/usr/share/help/oc/gnome-calculator/complex.page
/usr/share/help/oc/gnome-calculator/conv-base.page
/usr/share/help/oc/gnome-calculator/conv-character.page
/usr/share/help/oc/gnome-calculator/conv-currency.page
/usr/share/help/oc/gnome-calculator/conv-length.page
/usr/share/help/oc/gnome-calculator/conv-time.page
/usr/share/help/oc/gnome-calculator/conv-weight.page
/usr/share/help/oc/gnome-calculator/equation.page
/usr/share/help/oc/gnome-calculator/factorial.page
/usr/share/help/oc/gnome-calculator/factorize.page
/usr/share/help/oc/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/oc/gnome-calculator/financial.page
/usr/share/help/oc/gnome-calculator/functions.page
/usr/share/help/oc/gnome-calculator/history.page
/usr/share/help/oc/gnome-calculator/index.page
/usr/share/help/oc/gnome-calculator/keyboard.page
/usr/share/help/oc/gnome-calculator/legal.xml
/usr/share/help/oc/gnome-calculator/logarithm.page
/usr/share/help/oc/gnome-calculator/modulus.page
/usr/share/help/oc/gnome-calculator/mouse.page
/usr/share/help/oc/gnome-calculator/number-display.page
/usr/share/help/oc/gnome-calculator/percentage.page
/usr/share/help/oc/gnome-calculator/power.page
/usr/share/help/oc/gnome-calculator/scientific.page
/usr/share/help/oc/gnome-calculator/superscript.page
/usr/share/help/oc/gnome-calculator/trigonometry.page
/usr/share/help/oc/gnome-calculator/variables.page
/usr/share/help/pl/gnome-calculator/absolute.page
/usr/share/help/pl/gnome-calculator/base.page
/usr/share/help/pl/gnome-calculator/boolean.page
/usr/share/help/pl/gnome-calculator/complex.page
/usr/share/help/pl/gnome-calculator/conv-base.page
/usr/share/help/pl/gnome-calculator/conv-character.page
/usr/share/help/pl/gnome-calculator/conv-currency.page
/usr/share/help/pl/gnome-calculator/conv-length.page
/usr/share/help/pl/gnome-calculator/conv-time.page
/usr/share/help/pl/gnome-calculator/conv-weight.page
/usr/share/help/pl/gnome-calculator/equation.page
/usr/share/help/pl/gnome-calculator/factorial.page
/usr/share/help/pl/gnome-calculator/factorize.page
/usr/share/help/pl/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/pl/gnome-calculator/financial.page
/usr/share/help/pl/gnome-calculator/functions.page
/usr/share/help/pl/gnome-calculator/history.page
/usr/share/help/pl/gnome-calculator/index.page
/usr/share/help/pl/gnome-calculator/keyboard.page
/usr/share/help/pl/gnome-calculator/legal.xml
/usr/share/help/pl/gnome-calculator/logarithm.page
/usr/share/help/pl/gnome-calculator/modulus.page
/usr/share/help/pl/gnome-calculator/mouse.page
/usr/share/help/pl/gnome-calculator/number-display.page
/usr/share/help/pl/gnome-calculator/percentage.page
/usr/share/help/pl/gnome-calculator/power.page
/usr/share/help/pl/gnome-calculator/scientific.page
/usr/share/help/pl/gnome-calculator/superscript.page
/usr/share/help/pl/gnome-calculator/trigonometry.page
/usr/share/help/pl/gnome-calculator/variables.page
/usr/share/help/pt/gnome-calculator/absolute.page
/usr/share/help/pt/gnome-calculator/base.page
/usr/share/help/pt/gnome-calculator/boolean.page
/usr/share/help/pt/gnome-calculator/complex.page
/usr/share/help/pt/gnome-calculator/conv-base.page
/usr/share/help/pt/gnome-calculator/conv-character.page
/usr/share/help/pt/gnome-calculator/conv-currency.page
/usr/share/help/pt/gnome-calculator/conv-length.page
/usr/share/help/pt/gnome-calculator/conv-time.page
/usr/share/help/pt/gnome-calculator/conv-weight.page
/usr/share/help/pt/gnome-calculator/equation.page
/usr/share/help/pt/gnome-calculator/factorial.page
/usr/share/help/pt/gnome-calculator/factorize.page
/usr/share/help/pt/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/pt/gnome-calculator/financial.page
/usr/share/help/pt/gnome-calculator/functions.page
/usr/share/help/pt/gnome-calculator/history.page
/usr/share/help/pt/gnome-calculator/index.page
/usr/share/help/pt/gnome-calculator/keyboard.page
/usr/share/help/pt/gnome-calculator/legal.xml
/usr/share/help/pt/gnome-calculator/logarithm.page
/usr/share/help/pt/gnome-calculator/modulus.page
/usr/share/help/pt/gnome-calculator/mouse.page
/usr/share/help/pt/gnome-calculator/number-display.page
/usr/share/help/pt/gnome-calculator/percentage.page
/usr/share/help/pt/gnome-calculator/power.page
/usr/share/help/pt/gnome-calculator/scientific.page
/usr/share/help/pt/gnome-calculator/superscript.page
/usr/share/help/pt/gnome-calculator/trigonometry.page
/usr/share/help/pt/gnome-calculator/variables.page
/usr/share/help/pt_BR/gnome-calculator/absolute.page
/usr/share/help/pt_BR/gnome-calculator/base.page
/usr/share/help/pt_BR/gnome-calculator/boolean.page
/usr/share/help/pt_BR/gnome-calculator/complex.page
/usr/share/help/pt_BR/gnome-calculator/conv-base.page
/usr/share/help/pt_BR/gnome-calculator/conv-character.page
/usr/share/help/pt_BR/gnome-calculator/conv-currency.page
/usr/share/help/pt_BR/gnome-calculator/conv-length.page
/usr/share/help/pt_BR/gnome-calculator/conv-time.page
/usr/share/help/pt_BR/gnome-calculator/conv-weight.page
/usr/share/help/pt_BR/gnome-calculator/equation.page
/usr/share/help/pt_BR/gnome-calculator/factorial.page
/usr/share/help/pt_BR/gnome-calculator/factorize.page
/usr/share/help/pt_BR/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/pt_BR/gnome-calculator/financial.page
/usr/share/help/pt_BR/gnome-calculator/functions.page
/usr/share/help/pt_BR/gnome-calculator/history.page
/usr/share/help/pt_BR/gnome-calculator/index.page
/usr/share/help/pt_BR/gnome-calculator/keyboard.page
/usr/share/help/pt_BR/gnome-calculator/legal.xml
/usr/share/help/pt_BR/gnome-calculator/logarithm.page
/usr/share/help/pt_BR/gnome-calculator/modulus.page
/usr/share/help/pt_BR/gnome-calculator/mouse.page
/usr/share/help/pt_BR/gnome-calculator/number-display.page
/usr/share/help/pt_BR/gnome-calculator/percentage.page
/usr/share/help/pt_BR/gnome-calculator/power.page
/usr/share/help/pt_BR/gnome-calculator/scientific.page
/usr/share/help/pt_BR/gnome-calculator/superscript.page
/usr/share/help/pt_BR/gnome-calculator/trigonometry.page
/usr/share/help/pt_BR/gnome-calculator/variables.page
/usr/share/help/ro/gnome-calculator/absolute.page
/usr/share/help/ro/gnome-calculator/base.page
/usr/share/help/ro/gnome-calculator/boolean.page
/usr/share/help/ro/gnome-calculator/complex.page
/usr/share/help/ro/gnome-calculator/conv-base.page
/usr/share/help/ro/gnome-calculator/conv-character.page
/usr/share/help/ro/gnome-calculator/conv-currency.page
/usr/share/help/ro/gnome-calculator/conv-length.page
/usr/share/help/ro/gnome-calculator/conv-time.page
/usr/share/help/ro/gnome-calculator/conv-weight.page
/usr/share/help/ro/gnome-calculator/equation.page
/usr/share/help/ro/gnome-calculator/factorial.page
/usr/share/help/ro/gnome-calculator/factorize.page
/usr/share/help/ro/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/ro/gnome-calculator/financial.page
/usr/share/help/ro/gnome-calculator/functions.page
/usr/share/help/ro/gnome-calculator/history.page
/usr/share/help/ro/gnome-calculator/index.page
/usr/share/help/ro/gnome-calculator/keyboard.page
/usr/share/help/ro/gnome-calculator/legal.xml
/usr/share/help/ro/gnome-calculator/logarithm.page
/usr/share/help/ro/gnome-calculator/modulus.page
/usr/share/help/ro/gnome-calculator/mouse.page
/usr/share/help/ro/gnome-calculator/number-display.page
/usr/share/help/ro/gnome-calculator/percentage.page
/usr/share/help/ro/gnome-calculator/power.page
/usr/share/help/ro/gnome-calculator/scientific.page
/usr/share/help/ro/gnome-calculator/superscript.page
/usr/share/help/ro/gnome-calculator/trigonometry.page
/usr/share/help/ro/gnome-calculator/variables.page
/usr/share/help/ru/gnome-calculator/absolute.page
/usr/share/help/ru/gnome-calculator/base.page
/usr/share/help/ru/gnome-calculator/boolean.page
/usr/share/help/ru/gnome-calculator/complex.page
/usr/share/help/ru/gnome-calculator/conv-base.page
/usr/share/help/ru/gnome-calculator/conv-character.page
/usr/share/help/ru/gnome-calculator/conv-currency.page
/usr/share/help/ru/gnome-calculator/conv-length.page
/usr/share/help/ru/gnome-calculator/conv-time.page
/usr/share/help/ru/gnome-calculator/conv-weight.page
/usr/share/help/ru/gnome-calculator/equation.page
/usr/share/help/ru/gnome-calculator/factorial.page
/usr/share/help/ru/gnome-calculator/factorize.page
/usr/share/help/ru/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/ru/gnome-calculator/financial.page
/usr/share/help/ru/gnome-calculator/functions.page
/usr/share/help/ru/gnome-calculator/history.page
/usr/share/help/ru/gnome-calculator/index.page
/usr/share/help/ru/gnome-calculator/keyboard.page
/usr/share/help/ru/gnome-calculator/legal.xml
/usr/share/help/ru/gnome-calculator/logarithm.page
/usr/share/help/ru/gnome-calculator/modulus.page
/usr/share/help/ru/gnome-calculator/mouse.page
/usr/share/help/ru/gnome-calculator/number-display.page
/usr/share/help/ru/gnome-calculator/percentage.page
/usr/share/help/ru/gnome-calculator/power.page
/usr/share/help/ru/gnome-calculator/scientific.page
/usr/share/help/ru/gnome-calculator/superscript.page
/usr/share/help/ru/gnome-calculator/trigonometry.page
/usr/share/help/ru/gnome-calculator/variables.page
/usr/share/help/sl/gnome-calculator/absolute.page
/usr/share/help/sl/gnome-calculator/base.page
/usr/share/help/sl/gnome-calculator/boolean.page
/usr/share/help/sl/gnome-calculator/complex.page
/usr/share/help/sl/gnome-calculator/conv-base.page
/usr/share/help/sl/gnome-calculator/conv-character.page
/usr/share/help/sl/gnome-calculator/conv-currency.page
/usr/share/help/sl/gnome-calculator/conv-length.page
/usr/share/help/sl/gnome-calculator/conv-time.page
/usr/share/help/sl/gnome-calculator/conv-weight.page
/usr/share/help/sl/gnome-calculator/equation.page
/usr/share/help/sl/gnome-calculator/factorial.page
/usr/share/help/sl/gnome-calculator/factorize.page
/usr/share/help/sl/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/sl/gnome-calculator/financial.page
/usr/share/help/sl/gnome-calculator/functions.page
/usr/share/help/sl/gnome-calculator/history.page
/usr/share/help/sl/gnome-calculator/index.page
/usr/share/help/sl/gnome-calculator/keyboard.page
/usr/share/help/sl/gnome-calculator/legal.xml
/usr/share/help/sl/gnome-calculator/logarithm.page
/usr/share/help/sl/gnome-calculator/modulus.page
/usr/share/help/sl/gnome-calculator/mouse.page
/usr/share/help/sl/gnome-calculator/number-display.page
/usr/share/help/sl/gnome-calculator/percentage.page
/usr/share/help/sl/gnome-calculator/power.page
/usr/share/help/sl/gnome-calculator/scientific.page
/usr/share/help/sl/gnome-calculator/superscript.page
/usr/share/help/sl/gnome-calculator/trigonometry.page
/usr/share/help/sl/gnome-calculator/variables.page
/usr/share/help/sv/gnome-calculator/absolute.page
/usr/share/help/sv/gnome-calculator/base.page
/usr/share/help/sv/gnome-calculator/boolean.page
/usr/share/help/sv/gnome-calculator/complex.page
/usr/share/help/sv/gnome-calculator/conv-base.page
/usr/share/help/sv/gnome-calculator/conv-character.page
/usr/share/help/sv/gnome-calculator/conv-currency.page
/usr/share/help/sv/gnome-calculator/conv-length.page
/usr/share/help/sv/gnome-calculator/conv-time.page
/usr/share/help/sv/gnome-calculator/conv-weight.page
/usr/share/help/sv/gnome-calculator/equation.page
/usr/share/help/sv/gnome-calculator/factorial.page
/usr/share/help/sv/gnome-calculator/factorize.page
/usr/share/help/sv/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/sv/gnome-calculator/financial.page
/usr/share/help/sv/gnome-calculator/functions.page
/usr/share/help/sv/gnome-calculator/history.page
/usr/share/help/sv/gnome-calculator/index.page
/usr/share/help/sv/gnome-calculator/keyboard.page
/usr/share/help/sv/gnome-calculator/legal.xml
/usr/share/help/sv/gnome-calculator/logarithm.page
/usr/share/help/sv/gnome-calculator/modulus.page
/usr/share/help/sv/gnome-calculator/mouse.page
/usr/share/help/sv/gnome-calculator/number-display.page
/usr/share/help/sv/gnome-calculator/percentage.page
/usr/share/help/sv/gnome-calculator/power.page
/usr/share/help/sv/gnome-calculator/scientific.page
/usr/share/help/sv/gnome-calculator/superscript.page
/usr/share/help/sv/gnome-calculator/trigonometry.page
/usr/share/help/sv/gnome-calculator/variables.page
/usr/share/help/te/gnome-calculator/absolute.page
/usr/share/help/te/gnome-calculator/base.page
/usr/share/help/te/gnome-calculator/boolean.page
/usr/share/help/te/gnome-calculator/complex.page
/usr/share/help/te/gnome-calculator/conv-base.page
/usr/share/help/te/gnome-calculator/conv-character.page
/usr/share/help/te/gnome-calculator/conv-currency.page
/usr/share/help/te/gnome-calculator/conv-length.page
/usr/share/help/te/gnome-calculator/conv-time.page
/usr/share/help/te/gnome-calculator/conv-weight.page
/usr/share/help/te/gnome-calculator/equation.page
/usr/share/help/te/gnome-calculator/factorial.page
/usr/share/help/te/gnome-calculator/factorize.page
/usr/share/help/te/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/te/gnome-calculator/financial.page
/usr/share/help/te/gnome-calculator/functions.page
/usr/share/help/te/gnome-calculator/history.page
/usr/share/help/te/gnome-calculator/index.page
/usr/share/help/te/gnome-calculator/keyboard.page
/usr/share/help/te/gnome-calculator/legal.xml
/usr/share/help/te/gnome-calculator/logarithm.page
/usr/share/help/te/gnome-calculator/modulus.page
/usr/share/help/te/gnome-calculator/mouse.page
/usr/share/help/te/gnome-calculator/number-display.page
/usr/share/help/te/gnome-calculator/percentage.page
/usr/share/help/te/gnome-calculator/power.page
/usr/share/help/te/gnome-calculator/scientific.page
/usr/share/help/te/gnome-calculator/superscript.page
/usr/share/help/te/gnome-calculator/trigonometry.page
/usr/share/help/te/gnome-calculator/variables.page
/usr/share/help/uk/gnome-calculator/absolute.page
/usr/share/help/uk/gnome-calculator/base.page
/usr/share/help/uk/gnome-calculator/boolean.page
/usr/share/help/uk/gnome-calculator/complex.page
/usr/share/help/uk/gnome-calculator/conv-base.page
/usr/share/help/uk/gnome-calculator/conv-character.page
/usr/share/help/uk/gnome-calculator/conv-currency.page
/usr/share/help/uk/gnome-calculator/conv-length.page
/usr/share/help/uk/gnome-calculator/conv-time.page
/usr/share/help/uk/gnome-calculator/conv-weight.page
/usr/share/help/uk/gnome-calculator/equation.page
/usr/share/help/uk/gnome-calculator/factorial.page
/usr/share/help/uk/gnome-calculator/factorize.page
/usr/share/help/uk/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/uk/gnome-calculator/financial.page
/usr/share/help/uk/gnome-calculator/functions.page
/usr/share/help/uk/gnome-calculator/history.page
/usr/share/help/uk/gnome-calculator/index.page
/usr/share/help/uk/gnome-calculator/keyboard.page
/usr/share/help/uk/gnome-calculator/legal.xml
/usr/share/help/uk/gnome-calculator/logarithm.page
/usr/share/help/uk/gnome-calculator/modulus.page
/usr/share/help/uk/gnome-calculator/mouse.page
/usr/share/help/uk/gnome-calculator/number-display.page
/usr/share/help/uk/gnome-calculator/percentage.page
/usr/share/help/uk/gnome-calculator/power.page
/usr/share/help/uk/gnome-calculator/scientific.page
/usr/share/help/uk/gnome-calculator/superscript.page
/usr/share/help/uk/gnome-calculator/trigonometry.page
/usr/share/help/uk/gnome-calculator/variables.page
/usr/share/help/zh_CN/gnome-calculator/absolute.page
/usr/share/help/zh_CN/gnome-calculator/base.page
/usr/share/help/zh_CN/gnome-calculator/boolean.page
/usr/share/help/zh_CN/gnome-calculator/complex.page
/usr/share/help/zh_CN/gnome-calculator/conv-base.page
/usr/share/help/zh_CN/gnome-calculator/conv-character.page
/usr/share/help/zh_CN/gnome-calculator/conv-currency.page
/usr/share/help/zh_CN/gnome-calculator/conv-length.page
/usr/share/help/zh_CN/gnome-calculator/conv-time.page
/usr/share/help/zh_CN/gnome-calculator/conv-weight.page
/usr/share/help/zh_CN/gnome-calculator/equation.page
/usr/share/help/zh_CN/gnome-calculator/factorial.page
/usr/share/help/zh_CN/gnome-calculator/factorize.page
/usr/share/help/zh_CN/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/zh_CN/gnome-calculator/financial.page
/usr/share/help/zh_CN/gnome-calculator/functions.page
/usr/share/help/zh_CN/gnome-calculator/history.page
/usr/share/help/zh_CN/gnome-calculator/index.page
/usr/share/help/zh_CN/gnome-calculator/keyboard.page
/usr/share/help/zh_CN/gnome-calculator/legal.xml
/usr/share/help/zh_CN/gnome-calculator/logarithm.page
/usr/share/help/zh_CN/gnome-calculator/modulus.page
/usr/share/help/zh_CN/gnome-calculator/mouse.page
/usr/share/help/zh_CN/gnome-calculator/number-display.page
/usr/share/help/zh_CN/gnome-calculator/percentage.page
/usr/share/help/zh_CN/gnome-calculator/power.page
/usr/share/help/zh_CN/gnome-calculator/scientific.page
/usr/share/help/zh_CN/gnome-calculator/superscript.page
/usr/share/help/zh_CN/gnome-calculator/trigonometry.page
/usr/share/help/zh_CN/gnome-calculator/variables.page
/usr/share/help/zh_HK/gnome-calculator/absolute.page
/usr/share/help/zh_HK/gnome-calculator/base.page
/usr/share/help/zh_HK/gnome-calculator/boolean.page
/usr/share/help/zh_HK/gnome-calculator/complex.page
/usr/share/help/zh_HK/gnome-calculator/conv-base.page
/usr/share/help/zh_HK/gnome-calculator/conv-character.page
/usr/share/help/zh_HK/gnome-calculator/conv-currency.page
/usr/share/help/zh_HK/gnome-calculator/conv-length.page
/usr/share/help/zh_HK/gnome-calculator/conv-time.page
/usr/share/help/zh_HK/gnome-calculator/conv-weight.page
/usr/share/help/zh_HK/gnome-calculator/equation.page
/usr/share/help/zh_HK/gnome-calculator/factorial.page
/usr/share/help/zh_HK/gnome-calculator/factorize.page
/usr/share/help/zh_HK/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/zh_HK/gnome-calculator/financial.page
/usr/share/help/zh_HK/gnome-calculator/functions.page
/usr/share/help/zh_HK/gnome-calculator/history.page
/usr/share/help/zh_HK/gnome-calculator/index.page
/usr/share/help/zh_HK/gnome-calculator/keyboard.page
/usr/share/help/zh_HK/gnome-calculator/legal.xml
/usr/share/help/zh_HK/gnome-calculator/logarithm.page
/usr/share/help/zh_HK/gnome-calculator/modulus.page
/usr/share/help/zh_HK/gnome-calculator/mouse.page
/usr/share/help/zh_HK/gnome-calculator/number-display.page
/usr/share/help/zh_HK/gnome-calculator/percentage.page
/usr/share/help/zh_HK/gnome-calculator/power.page
/usr/share/help/zh_HK/gnome-calculator/scientific.page
/usr/share/help/zh_HK/gnome-calculator/superscript.page
/usr/share/help/zh_HK/gnome-calculator/trigonometry.page
/usr/share/help/zh_HK/gnome-calculator/variables.page
/usr/share/help/zh_TW/gnome-calculator/absolute.page
/usr/share/help/zh_TW/gnome-calculator/base.page
/usr/share/help/zh_TW/gnome-calculator/boolean.page
/usr/share/help/zh_TW/gnome-calculator/complex.page
/usr/share/help/zh_TW/gnome-calculator/conv-base.page
/usr/share/help/zh_TW/gnome-calculator/conv-character.page
/usr/share/help/zh_TW/gnome-calculator/conv-currency.page
/usr/share/help/zh_TW/gnome-calculator/conv-length.page
/usr/share/help/zh_TW/gnome-calculator/conv-time.page
/usr/share/help/zh_TW/gnome-calculator/conv-weight.page
/usr/share/help/zh_TW/gnome-calculator/equation.page
/usr/share/help/zh_TW/gnome-calculator/factorial.page
/usr/share/help/zh_TW/gnome-calculator/factorize.page
/usr/share/help/zh_TW/gnome-calculator/figures/org.gnome.Calculator.svg
/usr/share/help/zh_TW/gnome-calculator/financial.page
/usr/share/help/zh_TW/gnome-calculator/functions.page
/usr/share/help/zh_TW/gnome-calculator/history.page
/usr/share/help/zh_TW/gnome-calculator/index.page
/usr/share/help/zh_TW/gnome-calculator/keyboard.page
/usr/share/help/zh_TW/gnome-calculator/legal.xml
/usr/share/help/zh_TW/gnome-calculator/logarithm.page
/usr/share/help/zh_TW/gnome-calculator/modulus.page
/usr/share/help/zh_TW/gnome-calculator/mouse.page
/usr/share/help/zh_TW/gnome-calculator/number-display.page
/usr/share/help/zh_TW/gnome-calculator/percentage.page
/usr/share/help/zh_TW/gnome-calculator/power.page
/usr/share/help/zh_TW/gnome-calculator/scientific.page
/usr/share/help/zh_TW/gnome-calculator/superscript.page
/usr/share/help/zh_TW/gnome-calculator/trigonometry.page
/usr/share/help/zh_TW/gnome-calculator/variables.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgcalc-2.so.1
/usr/lib64/libgcalc-2.so.1.0.1
/usr/lib64/libgci-1.so.0
/usr/lib64/libgci-1.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gnome-calculator-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-calculator/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gcalccmd.1
/usr/share/man/man1/gnome-calculator.1

%files locales -f gnome-calculator.lang
%defattr(-,root,root,-)

